// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Person struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Ambition sql.NullString `json:"ambition"`
}

type Task struct {
	TaskID int64  `json:"task_id"`
	Todo   string `json:"todo"`
	Exp    int64  `json:"exp"`
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

type User struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Exp      int64  `json:"exp"`
	Level    int64  `json:"level"`
}
