// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: person.sql

package db

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO person (
  name, ambition
) VALUES (
  $1, $2
)
RETURNING id, name, ambition
`

type CreatePersonParams struct {
	Name     string         `json:"name"`
	Ambition sql.NullString `json:"ambition"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Name, arg.Ambition)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Ambition)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, ambition FROM person
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Ambition)
	return i, err
}

const getPersonByName = `-- name: GetPersonByName :one
SELECT id, name, ambition
FROM person
WHERE name = $1
`

func (q *Queries) GetPersonByName(ctx context.Context, name string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByName, name)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Ambition)
	return i, err
}
