// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: person.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO person (
  name, ambition
) VALUES (
  $1, $2
)
RETURNING id, name, ambition
`

type CreateAuthorParams struct {
	Name     string         `json:"name"`
	Ambition sql.NullString `json:"ambition"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Ambition)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Ambition)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, ambition FROM person
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Ambition)
	return i, err
}
