// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Person, error)
	GetAuthor(ctx context.Context, id int64) (Person, error)
}

var _ Querier = (*Queries)(nil)
