// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	GetPerson(ctx context.Context, id int64) (Person, error)
	GetPersonByName(ctx context.Context, name string) (Person, error)
}

var _ Querier = (*Queries)(nil)
