// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (
  todo, exp, user_id
) VALUES (
  $1, $2, $3
)
RETURNING task_id, todo, exp, user_id, status
`

type CreateTaskParams struct {
	Todo   string `json:"todo"`
	Exp    int64  `json:"exp"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Todo, arg.Exp, arg.UserID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Todo,
		&i.Exp,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const getCompleteTask = `-- name: GetCompleteTask :one
UPDATE task
SET status = "COMPLETE"
WHERE user_id = $1
RETURNING task_id, todo, exp, user_id, status
`

func (q *Queries) GetCompleteTask(ctx context.Context, userID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getCompleteTask, userID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Todo,
		&i.Exp,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const getTaskByUserId = `-- name: GetTaskByUserId :one
SELECT task_id, todo, exp, user_id, status
FROM task
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetTaskByUserId(ctx context.Context, userID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByUserId, userID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Todo,
		&i.Exp,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const getUndoneTaskByUserId = `-- name: GetUndoneTaskByUserId :one
SELECT task_id, todo, exp, user_id, status
FROM task
WHERE user_id = $1 AND status = "UNFINISHED"
LIMIT 1
`

func (q *Queries) GetUndoneTaskByUserId(ctx context.Context, userID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getUndoneTaskByUserId, userID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Todo,
		&i.Exp,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT task_id, todo, exp, user_id, status FROM task
WHERE user_id = $1
ORDER BY task_id DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Todo,
			&i.Exp,
			&i.UserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE task
SET status = $2
WHERE task_id = $1
RETURNING task_id, todo, exp, user_id, status
`

type UpdateTaskStatusParams struct {
	TaskID int64  `json:"task_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.TaskID, arg.Status)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Todo,
		&i.Exp,
		&i.UserID,
		&i.Status,
	)
	return i, err
}
