// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const addUserExp = `-- name: AddUserExp :one
UPDATE users
SET exp = exp + $2
WHERE user_id = $1
RETURNING user_id, username, password, exp, level
`

type AddUserExpParams struct {
	UserID int64 `json:"user_id"`
	Exp    int64 `json:"exp"`
}

func (q *Queries) AddUserExp(ctx context.Context, arg AddUserExpParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUserExp, arg.UserID, arg.Exp)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Exp,
		&i.Level,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, password
) VALUES (
  $1, $2
)
RETURNING user_id, username, password, exp, level
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Exp,
		&i.Level,
	)
	return i, err
}

const getUserByUserId = `-- name: GetUserByUserId :one
SELECT user_id, username, password, exp, level
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByUserId(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserId, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Exp,
		&i.Level,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, password, exp, level
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Exp,
		&i.Level,
	)
	return i, err
}
